{% set name = "jpmml-sparkml" %}
{% set version = "2.3.2" %}
{% set sha256 = "4859bd5a2aaf3bcf0ee35182b94a7cfd6ef253795d6bf38bcaed38e41f61a69a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jpmml/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  skip: True # [not linux64]

requirements:
  host:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
    - maven 3.*
    - ninja
    - openjdk 8.*
    - swig
  run:
    - openjdk 8.*

test:
  commands:
    - test -f $PREFIX/share/java/pmml-sparkml-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-example-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-lightgbm-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-xgboost-{{ version }}.jar

about:
  home: https://github.com/jpmml/jpmml-sparkml
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: |
    Java library and command-line application for converting Apache Spark ML pipelines to PMML.
  description: |
    Java library and command-line application for converting Apache Spark ML pipelines to PMML.
  doc_url: https://github.com/jpmml/jpmml-sparkml
  dev_url: https://github.com/jpmml/jpmml-sparkml

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/66320
  recipe-maintainers:
    - ianaobi
    - bkreider
    - amaloney
