{% set name = "pyspark2pmml" %}
{% set version = "0.5.1" %}
{% set sha256 = "426b2d4752d8c201cde533723972c8749aa2a40371f725d85d1524a2bb73ed03" %}
{% set jpmml_name = "jpmml-sparkml" %}
{% set jpmml_version = "2.3.5" %}
{% set jpmml_sha256 = "c69cce99fb09d2e5a729e9d25964b5cf41826f38c06e2fbc859bdfefd2bae42d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/jpmml/{{ jpmml_name }}/archive/refs/tags/{{ jpmml_version }}.tar.gz
    folder: jars
    sha256: {{ jpmml_sha256 }}
    patches:
      - patches/0001-maven-plugin-addition.patch
  - url: https://github.com/microsoft/LightGBM/releases/download/v3.3.5/LightGBM-complete_source_code_tar_gz.tar.gz
    folder: lightgbm
    sha256: 2a08ad905533a9fcc9c9551e06e7c12532d86cd22d9fe1aa0f6fc126ab53be77

build:
  noarch: python
  number: 3
  skip: True # [not linux64]

requirements:
  host:
    - pip
    - python
    - wheel
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
    - maven 3.*
    - ninja
    - openjdk 8.*
    - swig
    - patch # [linux64]
  run:
    - py4j
    - python

test:
  requires:
    - pip
    - py4j
    - pyspark
    - python <3.11
  imports:
    - pyspark.ml
  commands:
    - pip check
    - test -f $PREFIX/share/java/pmml-sparkml-{{ jpmml_version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-example-{{ jpmml_version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-lightgbm-{{ jpmml_version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-xgboost-{{ jpmml_version }}.jar

about:
  home: https://github.com/jpmml/pyspark2pmml
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Python library for converting Apache Spark ML pipelines to PMML.
  description: Python library for converting Apache Spark ML pipelines to PMML.
  doc_url: https://github.com/jpmml/pyspark2pmml
  dev_url: https://github.com/jpmml/pyspark2pmml

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/34209
      - https://anaconda.zendesk.com/agent/tickets/66320
  recipe-maintainers:
    - ianaobi
    - bkreider
    - amaloney
