{% set version = "1.6.5" %}
{% set sha256 = "" %}

package:
  name: jpmml-sparkml
  version: {{ version }}

source:
  url: https://repo1.maven.org/maven2/org/jpmml/jpmml-sparkml/{{ version }}/jpmml-sparkml-{{ version }}.jar
  #sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk
  run:
    - openjdk


about:
  home: https://github.com/jpmml/jpmml-sparkml
  summary: "PMML support for Apache Spark ML pipelines"
  license: "AGPL-3.0"
  license_family: AGPL
  license_file: LICENSE.txt
  summary: "Java library for converting Apache Spark ML pipelines to PMML"
  description: "Java app for converting Apache Spark ML pipelines to PMML."
  doc_url: https://github.com/jpmml/jpmml-sparkml
  dev_url: https://github.com/jpmml/jpmml-sparkml

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/34209
  recipe-maintainers:
    - bradley
