{% set name = "jpmml-sparkml" %}
{% set version = "3.1.0" %}
{% set sha256 = "93294b0354ca95f1536ce5d17c22d7176c6088e8ce9e152fd6085d432544699f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jpmml/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  skip: True # [not linux64]

requirements:
  host:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
    - maven 3.*
    - ninja
    - openjdk 11.*
    - swig
  run:
    - openjdk 11.*

test:
  commands:
    - test -f $PREFIX/share/java/pmml-sparkml-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-evaluator-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-example-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-lightgbm-{{ version }}.jar
    - test -f $PREFIX/share/java/pmml-sparkml-xgboost-{{ version }}.jar

about:
  home: https://github.com/jpmml/jpmml-sparkml
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: |
    Java library and command-line application for converting Apache Spark ML pipelines to PMML.
  description: |
    Java library and command-line application for converting Apache Spark ML pipelines to PMML.
  doc_url: https://github.com/jpmml/jpmml-sparkml
  dev_url: https://github.com/jpmml/jpmml-sparkml

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/66320
  recipe-maintainers:
    - bkreider
    - amaloney
